AWSTemplateFormatVersion: 2010-09-09
Description: Root stack template for AWS CloudFormation Step by Step series.

Parameters:
  DbClass:
    Type: String 
    AllowedValues: [ db.t2.micro, db.t2.small ]
    Description: RDS DB instance class for the DB storage
    Default: db.t2.micro

Resources:
  NetworkStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'network-template.yaml'

  StorageStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: 'storage-template.yaml'
      Parameters:
        DbClass: !Ref DbClass
        DbSecurityGroup: !GetAtt NetworkStack.Outputs.DbSecurityGroup
        DbSubnets: !GetAtt NetworkStack.Outputs.PrivateSubnets
